ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - tolgee-staging.logora.fr
      secretName: tolgee-staging-tls
  hosts:
    - host: "tolgee-staging.logora.fr"
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    memory: "512Mi"
  requests:
    memory: "256Mi"

postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres-staging-password"
    username: "tolgee"
    password: "tolgee-staging-password"
    database: "tolgee"
  primary:
    persistence:
      enabled: true
      storageClass: "csi-cinder-high-speed"
      size: 8Gi
    resources:
      limits:
        memory: "512Mi"
      requests:
        memory: "256Mi"
