mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: "latest"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    kubeletstats:
      collection_interval: 15s
      auth_type: "serviceAccount"
      endpoint: "https://${K8S_NODE_IP}:10250"
      insecure_skip_verify: true
      metric_groups:
        - pod
        - node
        - container
    filelog:
      include:
        - /var/log/pods/*/*/*.log
      exclude:
        - /var/log/pods/monitoring_*/*/*.log
        - /var/log/pods/kube-system_*/*/*.log
        - /var/log/pods/kube-public_*/*/*.log
        - /var/log/pods/kubernetes-dashboard_*/*/*.log
        - /var/log/pods/ingress-nginx_*/*/*.log
        - /var/log/pods/cert-manager_*/*/*.log
      start_at: beginning
      include_file_path: true
      operators:
        - type: container
        - type: json_parser
          parse_from: body
          timestamp:
            parse_from: attributes.time
            layout: 'ms'
            layout_type: epoch

  processors:
    filter/drop_k8s_namespaces:
      metrics:
        exclude:
          match_type: regexp
          resource_attributes:
            - key: k8s.namespace.name
              value: (kube-system|kube-public|cert-manager)
    cumulativetodelta:
    batch:
      send_batch_max_size: 10000
      timeout: 10s
    resourcedetection:
      detectors: [env, system]
    k8sattributes:
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.container.name
          - k8s.deployment.name
          - k8s.node.name
          - container.image.name
          - container.image.tag
      pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
    attributes/set_service_name:
      actions:
        - key: service.name
          from_attribute: k8s.container.name
          action: upsert
    attributes/copy_target_to_route:
      actions:
        - key: http.route
          from_attribute: http.target
          action: upsert

  exporters:
    debug:
      verbosity: detailed
    otlp/uptrace:
      endpoint: https://otlp.uptrace.dev:4317
      tls: { insecure: false }
      headers:
        uptrace-dsn: ${UPTRACE_DSN}

  service:
    pipelines:
      metrics:
        receivers: [kubeletstats]
        processors: [filter/drop_k8s_namespaces, cumulativetodelta, batch, resourcedetection]
        exporters: [otlp/uptrace]
      logs:
        receivers: [filelog]
        processors: [k8sattributes, attributes/set_service_name, batch, resourcedetection]
        exporters: [otlp/uptrace]
      traces:
        receivers: [otlp]
        processors: [attributes/copy_target_to_route, k8sattributes, batch, resourcedetection]
        exporters: [otlp/uptrace, debug]

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true
  name: otel-collector

extraEnvs:
  - name: K8S_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UPTRACE_DSN
    valueFrom:
      secretKeyRef:
        name: otel-collector-secrets
        key: UPTRACE_DSN

extraVolumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods
      type: Directory

extraVolumeMounts:
  - name: varlogpods
    mountPath: /var/log/pods
    readOnly: true

service:
  enabled: true
  type: ClusterIP