mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: "latest"

config:
  receivers:
    kubeletstats:
      collection_interval: 30s
      auth_type: "serviceAccount"
      endpoint: "https://${K8S_NODE_IP}:10250"
      insecure_skip_verify: true
      metric_groups:
        - pod
        - node
        - container
    filelog:
      include:
        - /var/log/pods/*/*/*.log
      exclude:
        - /var/log/pods/monitoring_*/*/*.log
        - /var/log/pods/kube-system_*/*/*.log
        - /var/log/pods/kube-public_*/*/*.log
        - /var/log/pods/kubernetes-dashboard_*/*/*.log
        - /var/log/pods/ingress-nginx_*/*/*.log
        - /var/log/pods/cert-manager_*/*/*.log
      start_at: beginning
      include_file_path: true
      operators:
        - type: container
        - type: json_parser
          parse_from: body
          timestamp:
            parse_from: attributes.time
            layout: 'ms'
            layout_type: epoch

  processors:
    batch:
      send_batch_max_size: 100
      send_batch_size: 10
      timeout: 10s
    resourcedetection:
      detectors: [env, system]
    k8sattributes:
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.container.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.node.name
        labels:
          - key: app
          - key: app.kubernetes.io/name
          - key: app.kubernetes.io/instance
          - key: app.kubernetes.io/component
      pod_association:
        - sources:
            - from: resource_attribute
              name: k8s.pod.name
            - from: resource_attribute
              name: k8s.namespace.name
      passthrough: false
    attributes/set_service_name:
      actions:
        - key: service.name
          from_attribute: app.kubernetes.io/name
          action: upsert

  exporters:
    debug:
      verbosity: detailed
    otlp/uptrace:
      endpoint: https://otlp.uptrace.dev:4317
      tls: { insecure: false }
      headers:
        uptrace-dsn: ${UPTRACE_DSN}

  service:
    pipelines:
      metrics:
        receivers: [kubeletstats]
        processors: [batch, resourcedetection]
        exporters: [otlp/uptrace]
      logs:
        receivers: [filelog]
        processors: [k8sattributes, attributes/set_service_name, batch, resourcedetection]
        exporters: [otlp/uptrace]

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true
  name: otel-collector

extraEnvs:
  - name: K8S_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UPTRACE_DSN
    valueFrom:
      secretKeyRef:
        name: otel-collector-secrets
        key: UPTRACE_DSN

extraVolumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods
      type: Directory

extraVolumeMounts:
  - name: varlogpods
    mountPath: /var/log/pods
    readOnly: true